### ISSUE TITLE
RuntimeError: Unreachable

### ISSUE THREAD

**Issue by Githubber828** [igorlira/dirplayer-rs#6]
Hello, 

Having some issues - when I browse to http://IP:3000.. the movie URL appears and then when I hit load I get the following error:

Uncaught runtime errors:
×
ERROR
unreachable
RuntimeError: unreachable
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[495]:0x8beed
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[986]:0xbd501
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[667]:0x9a078
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[813]:0xab61e
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[384]:0x7eae2
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[1204]:0xc99a1
    at http://<ipaddress>:3000/static/media/vm_rust_bg.3c1ee51bbd4deb41203c.wasm:wasm-function[1181]:0xc9702
    at __wbg_adapter_31 (http://<ipaddress>:3000/static/js/bundle.js:73842:8)
    at real (http://<ipaddress>:3000/static/js/bundle.js:73824:14)

**Comment by igorlira** [comment]
Can you post the full message of the first error message that shows up on your console? That will tell which file and line the error came from

**Comment by Githubber828** [comment]
> Can you post the full message of the first error message that shows up on your console? That will tell which file and line the error came from

Hello, there doesn't appear to be any errors on the console. The error above is on the webpage only

![image](https://github.com/igorlira/dirplayer-rs/assets/173944991/ec1ae618-d3e8-4141-be53-16f1798e6393)

**Comment by igorlira** [comment]
Sorry, I meant your browser console. It will look like this:

<img width="995" alt="image" src="https://github.com/igorlira/dirplayer-rs/assets/4934870/cc66fef0-d6c2-4547-915f-241d9b2efebe">

**Comment by Githubber828** [comment]
> Sorry, I meant your browser console. It will look like this:
> 
> <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/4934870/343988880-cc66fef0-d6c2-4547-915f-241d9b2efebe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzUyMjAsIm5iZiI6MTcxOTg3NDkyMCwicGF0aCI6Ii80OTM0ODcwLzM0Mzk4ODg4MC1jYzY2ZmVmMC1kNmMyLTQ1NDctOTE1Zi0yNDFkOWIyZWZlYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMjMwMjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkzNjI3YTFkYzFkZmIxYjQ2MjgyN2I5OWZhN2ZhMGE5ZmMzY2RhOGEwNzE4YjczMzQyOTg5ZjJkMmJmMDNlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EbBEcFSQ5PbEBI8_cZ9eEo-6WMeCQnMK3nuAzXxDUcU">

Hello,

Please see the error below:

![image](https://github.com/igorlira/dirplayer-rs/assets/173944991/3a6263f4-aa18-42d7-bd8e-e7250d741417)

**Comment by markhughes** [comment]
@Githubber828 Reload with the network panel open, is it being blocked by CORS?

**Comment by chameleonxxl** [comment]
Closing this issue, its very old and might be not happening again.

If the problem still happens, please reopen the issue!
